### ISSUE TITLE
Database not add sql

### ISSUE THREAD

**Issue by SSnarKW** [ArmaLife/Framework#630]
DELIMITER $$--
-- Procedures
-- Edit arma3 to match a user in MySQL
-- For external databases: Edit localhost to match arma3server IP
--
CREATE DEFINER =  `root`@`localhost` PROCEDURE  `resetLifeVehicles` ( ) BEGIN UPDATE  `vehicles` SET  `active` =0;

END$$

MySQL said: Documentation

#1304 - PROCEDURE resetLifeVehicles already exists

**Comment by tkcjesse** [comment]
Whats your problem here?

**Comment by SSnarKW** [comment]
Sir when i add sql it's said me Error look sql if was error

**Comment by Liam0** [comment]
it's because you already have the PROCEDURE just start by removing all the procedures in ur old database before importing the .sql

**Comment by tkcjesse** [comment]
Yep. So as I said, as well as Liam...

https://i.gyazo.com/355d5b788ed35daab515a2a0752bdac4.png

Just delete the stored procedures. Or leave them if you didn't change them, this is just a warning and nothing to worry about if you didn't change the procedure.

Closing issue since it's not related to main build or an issue at all..
