### ISSUE TITLE
Arresting Location

### ISSUE THREAD

**Issue by BoGuu** [ArmaLife/Framework#660]
Suggestion:

Add a config option for the location in which somebody is arrested. Currently you must arrest people from a police station, however, I would imagine a lot of servers would prefer to drive them to the jail and arrest them there.

So a config option for stations or at the jail would be handy!

**Comment by Jawshy** [comment]
Why not just add `jail_marker` to [fn_copInteractionMenu.sqf, line 88](https://github.com/ArmaLife/Framework/blob/946a74f06960e27c178eaa673b948baa5abc3ff3/Altis_Life.Altis/core/cop/fn_copInteractionMenu.sqf#L88) instead of adding a superfluous option to the Master_Config.hpp?

**Comment by BoGuu** [comment]
@Jawshy 

And if people don't want to be able to jail from the stations?

**Comment by Repentz** [comment]
Remove the marker calls in the interaction menu and replace them with ones you place on the map near your jail. therefore you cannot send people to jail at the stations.

**Comment by sargken** [comment]
Just make it a array in the config and people can add or remove marker names and if they cant figure it out too bad. You guys make no since. If people don't want their cops to arrest at jail its an easy fix that server owners should know how to do. If they can't do that they should own a server in my opinion.  I agree with @Jawshy on the matter.

**Comment by Heavybob** [comment]
The purpose of the master_config is to consolidate all the possible variables that can be modified and put them into an easy to find place.

**Comment by tkcjesse** [comment]
^ Orlly?
