### ISSUE TITLE
extDB2

### ISSUE THREAD

**Issue by SGCAtlantis** [ArmaLife/Framework#777]
I have changed my name db altislife for custom to altislife.sql and created my db
but I have error 

extDB2: Found extdb-conf.ini
extDB2: Detected 4 Cores, Setting up 4 Worker Threads

[07:54:35:347696 +02:00] [Thread 6236] extDB2: No Config Option Found: altislife
[07:55:41:806497 +02:00] [Thread 6236] extDB2: Stopping ...

**Comment by Jawshy** [comment]
Did you change the name "altislife" to your custom database name in all of the respective files (extdb-conf.ini, etc.)? 

Also, this issue is not related to the current build; it is a personal issue. So in future, please use our [support chat-room on Gitter](https://gitter.im/ArmaLife/Framework/Support), [our Discord server](https://discordapp.com/invite/0z4k0hcAcvMl2SQx), or post on the [Altis Life RPG Forums](http://www.altisliferpg.com/).

**Comment by SGCAtlantis** [comment]
I have changed the name to @extDB2/extdb-conf.ini
and  altislife.sql

and I see in V 4.4R2 to life_server/config.cpp
we have 
class Life_Server_Settings {
	class EXTDB {
		DatabaseName = "";  <- Custom name data here

but to V 4.4R3 we have just 
class CfgFunctions {
    class MySQL_Database {
        tag = "DB";
        class MySQL

**Comment by GetSomePanda** [comment]
Yeah they changed this awhile back, they just put it in a new location.
Its in the description.ext btw.
https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/description.ext

Under the CfgServer class.
Database = "altislife";

Then make sure in your extdb-conf.ini the sql directory is [AltisLife]

**Comment by SGCAtlantis** [comment]
ho I hadn't seen it this in  description.ext

thx work great now
