### ISSUE TITLE
fn_restrain.sqf

### ISSUE THREAD

**Issue by JohnConry** [ArmaLife/Framework#835]
Hi,

How can we add serflex to civilian, in order to allow them to restrain cops ? :c

**Comment by Latouth** [comment]
Quick question, how is this an issue?
And it's easy to make them be able to restrain cops/civs.
Just copy the restrain, make it fn_restrainCiv.sqf and do the same with the other restrain script.
Then set checks to civilian, possibly add an item (like handcuffs or zipties) that they need to have in order to use it.
And b000m
